global.name = "FRISK"; //Player's Name
global.level = 1; //Player's Level
global.location = "Test Zone"; //Player's Location
global.maxHP = 20; //Player's Max Health
global.hp = global.maxHP //Player's Current Health
global.xp = 0;
global.xp_gain = 0;
global.gold = 0;
global.gold_gain = 0;
global.def = 0; //Player's Def
global.firstRoom = room_intro; //First Room
global.IngameTimer = 0; //In-game Timer in Seconds
